### ISSUE TITLE
Vanilla Nightly

### ISSUE THREAD

**Issue by airon90** [vanilla-music/vanilla-music-lyrics-search#1]
Does it work on Vanilla Nightly too? It seems that there is no "Plugins" option in library screen

**Comment by Kaned1as** [comment]
Haven't tried with nightly yet, but plugin system is already merged.

Can you post some screenshots?
Plugins option should be visible on song long click context menu.

**Comment by airon90** [comment]
![tmp_12957-screenshot_2017-01-12-14-34-49-1256767064](https://cloud.githubusercontent.com/assets/139841/21891746/6c80cbde-d8d4-11e6-9178-7754c7d0439e.png)

This is the screenshot of Library Screen section in Settings

**Comment by taranarmo** [comment]
![screenshot_20170112-164933](https://cloud.githubusercontent.com/assets/11619234/21892399/be287f64-d8e7-11e6-969e-eb7b59783f34.png)
Vanilla music and lyrics plugin installed from f-droid

**Comment by airon90** [comment]
This is the screenshot of the context menu by long pressing on a song
![tmp_16216-screenshot_2017-01-12-16-05-44-1256767064](https://cloud.githubusercontent.com/assets/139841/21894861/0031059a-d8e1-11e6-88ab-caf6d0131fed.png)

**Comment by Kaned1as** [comment]
@adrian-bl , can you please tell from which sources is vanilla nightly built?
Can't test it right now.

**Comment by adrian-bl** [comment]
It gets build from the git head every 24 hours - but uses a different package name.

This script is used to build it: https://gist.github.com/adrian-bl/f844e936c3154d729557e9d4ba8d0b87, so the plugin action constants also get renamed

**Comment by Kaned1as** [comment]
@Airon90 , as @adrian-bl said, the packages are renamed in Nightly so it can't communicate with pliguns.
I suggest to wait a bit for official release (or maybe include plugins in Nightly builds too?).

**Comment by adrian-bl** [comment]
I could upload a test version using the real package name signed with the play store release key if it helps.

(= you could upgrade without uninstalling if you installed vanilla music from the play store)

**Comment by PanderMusubi** [comment]
Same problem here via F-Droid. Willing to help with testing when new build is there.

**Comment by Kaned1as** [comment]
Signed with my GPlay release key: [vanilla-music-11.01.2017.apk.zip](https://github.com/vanilla-music/vanilla-music-lyrics-search/files/705141/vanilla-music-11.01.2017.apk.zip), built from commit [c270b13](https://github.com/vanilla-music/vanilla/commit/c270b13296f2ee6acd69d861404dd9d2deeb91dc)

**Comment by adrian-bl** [comment]
Btw: I just pushed tag 1.0.47, so an f-droid build (signed with their key) should surface in a few hours.

I'll probably *not* release 1.0.47 on the play store as it still has some rought edges (but it's good enoug for f-droid -> f-droid users are more tech savvy and always have the option to downgrade if there is a serious bug) - so the next play-store release will be 1.0.48 (which is probably just .47 + bugfixes)

**Comment by Kaned1as** [comment]
Is this still relevant?

**Comment by adrian-bl** [comment]
No, i think we can close this: There is little reason to use the nightly build to test plugin features.

**Comment by PanderMusubi** [comment]
Longpress track - Plugins - Lyrics search works now in app from F-Droid. Thanks.

**Comment by airon90** [comment]
I long press a track but I can't find the "Plugins" option again.

**Comment by Kaned1as** [comment]
@Airon90 , do you use Nightly or F-Droid build?
