### ISSUE TITLE
F-Droid - Version 1.3.3 (13) need to update

### ISSUE THREAD

**Issue by ChiefMikeK** [vanilla-music/vanilla-music-lyrics-search#13]
[Vanilla Lyrics Search | F-Droid - Android App Repository](https://f-droid.org/en/packages/com.kanedias.vanilla.lyrics/)
---
Signatures incompatible with alternative download sites so I'm unable to update 🐣

**Comment by Kaned1as** [comment]
F-Droid updates applications by themselves, I have no control over it

**Comment by Kaned1as** [comment]
What I mean is: you better ask this question in `#fdroid:f-droid.org` Matrix chat
