### ISSUE TITLE
Lyrics search from menu in 'Now playing'

### ISSUE THREAD

**Issue by PanderMusubi** [vanilla-music/vanilla-music-lyrics-search#2]
Please,also offer lyrics search from menu in 'Now playing'. Otherwise, users always have to go to the track in the library to get lyrics.

**Comment by Kaned1as** [comment]
Oh-ho-ho, ok. This issue belongs more to vanilla repo, because code changes will be on the player side.
Anyway, I'll see what I can do. This or next weekend.

@adrian-bl , what are your thoughts on adding one more menu entry to Now Playing screen?

**Comment by adrian-bl** [comment]
Having the 'Plugins' option in the FullPlaybackActivity context menu wouldn't hurt

**Comment by Kaned1as** [comment]
Guess this can be closed, @PanderMusubi, what d'you think?

**Comment by PanderMusubi** [comment]
Yes, context menu for FullPlaybackActivity offers this now. Thanks.
