### ISSUE TITLE
Feature req: write to sdcard

### ISSUE THREAD

**Issue by rosc2112** [vanilla-music/vanilla-music-lyrics-search#4]
Hi. Just want to ask if you could add the permission to write to external sdcard. The lyrics can't be saved in the same directory as the mp3s. Being able to browse or configure the default save location to other dirs for saving would be helpful.

Btw, where do the lyrics get saved by default? I copied a test mp3 to the internal drive /sdcard0/Downloads, the file is successfully saved but where? I can't find it, if its in a hidden system dir.

**Comment by Kaned1as** [comment]
Lyrics is saved inside a file, in an USLT ID3 tag. This is done through Tag Editor plugin.

Lyrics fetcher doesn't have permissions to work with files at all

**Comment by Kaned1as** [comment]
You should now be able to persist lyrics into *.lrc file in sdcard.
