### ISSUE TITLE
Feature req: read local .lrc files (minilyrics) 

### ISSUE THREAD

**Issue by dapgo** [vanilla-music/vanilla-music-lyrics-search#5]
I think that reading time lyrics from local .lrc files or id tags would be an awesome feature.

[https://en.wikipedia.org/wiki/LRC_%28file_format%29](https://en.wikipedia.org/wiki/LRC_%28file_format%29)

**Comment by Kaned1as** [comment]
Our integration with vanilla-music is very thin. Basically player can only throw a file at us and say "deal with it".  We have no clue how to synchronize lyrics with audio stream if we don't see the stream itself.

Adrian (the author of vanilla) objected to the inclusion of lyrics search as part of player saying that it would make player bloated. He has his reasons and I coudn't persuade him.

The only thing we can do is read lrc file and just display lyrics as a text. Will that suffice?

**Comment by dapgo** [comment]
First of all, I don't know how vanilla plugins work or limitations so my next lines can be out of sense...

But I think that you don't need access to the stream, supposing that the plugin receives the file as soon as it is loaded (lets say 0,2 sec), then you have with a big precision(1) the start of the song.
 
And supposing that the plugin is being continuously executed and it can access to a timer function, then you would have the current time/position of this song. (2)
So, you only need to compare with the next time tag and then display the string.

(1) Precision is not so important as in film subtitles, even some players displays previous, current and next string.
(2) As least until the user pause the song, it can be a problem if the plugin is not notified of this event

Anyway, even displaying the lrc file content with no synchronization seams quite useful. ;)
Thanks for your work

**Comment by Kaned1as** [comment]
Ok, now we can read lyrics from *.lrc files and persist to them.
Wait for F-Droid update on this (or are you using Google Play?)

Sjould I close this issue or is there anything else I missed?

**Comment by dapgo** [comment]
I have from F-Droid, but if the new version is in Play I can install and test it.
BTW, and just for personal curiosity. does vanilla plugins require installation from an apk? what about copying plugin files in a vanilla folder?

**Comment by Kaned1as** [comment]
Yep, they do, they are just ordinary apps that are designed to interoperate with Vanilla.

No, I didn't push update to GPlay yet.

**Comment by Kaned1as** [comment]
Must be in F-Droid for quite a while now. Closing.
