### ISSUE TITLE
Lyrics window size in version 1.2.0

### ISSUE THREAD

**Issue by FrancoisMz** [vanilla-music/vanilla-music-lyrics-search#7]
Hello,
in version 1.2.0,  a clean dialog window has been added in case no lyrics are found. For this, a default, fixed window size has been defined (as the lyrics field is empty anyway).
However, this default, fixed window size is also applied when lyrics are available, whereas the previous behaviour until 1.1.0 was to have a self-adaptative size depending on the number of lyrics lines.
Consequence is that only 5 or 6 lines of the lyrics are visible, which can be a pain for long text and is a pity on a large tablet screen e.g.
--> would it be possible to use the fixed window size only when no lyrics are available and to use the previous self-adaptative size when lyrics are available ?
Thank you in advance.

**Comment by Kaned1as** [comment]
@FrancoisMz that was the unfortunate consequence of having an actionbar at the top.

I'll have a look at the possibility to restore adaptive size detection this week.

**Comment by Kaned1as** [comment]
Should be fixed in 1.2.2. Can you grab it from Releases page to test please?

**Comment by FrancoisMz** [comment]
Hello,
tested it on a smart phone and a tablet.
Works perfectly well in both cases. It seems the lyrics field is even bigger than before.
Very nice, thank you.
